Usunięto śmieci
Lakasabasz/TrainStationRepo pull request #2
Opened 2024-08-08 13:28 UTC by TheMultii

Closes #1

2024-08-08 13:32 UTC, Lakasabasz requested changes
Zamiast usunąć śmieci dodałeś nowe

2024-08-08 13:32 UTC, Lakasabasz commented on main.go
> +}
Napisz to w czymś lepszym. Np. w C#

2024-08-08 13:35 UTC, TheMultii commented on main.go
> +}
teraz jest lepiej

2024-08-08 13:39 UTC, TheMultii reviewed
LGTM 🚀

2024-08-14 10:24 UTC, TheMultii commented
where merge

2024-08-26 12:38 UTC, TheMultii commented
Fuck you

2024-08-26 12:38 UTC, closed without merging